xdsl: make flake8 happy with our source files (#198)
* all lines 90 columns or less

* ignore rule E402 in flake8: module level import not at top of file

* resolve all E502 introduced earlier

* remove unused imports

* remove blank line with whitespace

* fix E128 continuation line under-indented for visual indent

* fix W291 trailing whitespace

* fix E251 unexpected spaces around keyword / parameter equals

* fix F541 f-string is missing placeholders

* fix F841 local variable $var is assigned to but never used

* fix E126 continuation line over-indented for hanging indent

* fix F402 import 'field' from line 6 shadowed by loop variable

* fix E123 closing bracket does not match indentation of opening bracket's line

* fix E265 block comment should start with '# '

* fix E129 visually indented line with same indent as next logical line

* fix F811 redefinition of unused 'UnitAttr' from line 141

* fix E302 expected 2 blank lines, found 1

* fix E999 SyntaxError: unexpected character after line continuation character