tests: Add main and filecheck tests for Toy (#867)
I'm having trouble getting filecheck to cooperate. It refuses to run
tests outside `tests/filecheck`, as far as I can tell, do you know what
might be causing this?

```
(venv) (base) sasha@SL-MBP-16 ~/D/x/xdsl> lit -v docs/Toy/examples/ast.toy                                                           sasha/toy/filecheck!
lit: /Users/sasha/Developer/xdslproject/xdsl/venv/lib/python3.11/site-packages/lit/discovery.py:132: warning: unable to find test suite for 'docs/Toy/examples/ast.toy'
lit: /Users/sasha/Developer/xdslproject/xdsl/venv/lib/python3.11/site-packages/lit/discovery.py:281: warning: input 'docs/Toy/examples/ast.toy' contained no tests
error: did not discover any tests for provided path(s)
```

Running the copy in `filecheck/frontend` works fine