core: Fix location in func block arguments (#5690)
func.func block arguments having locations info are not parsed in xDSL
and hence throws parsing errors.
```mlir
func.func @f_attrs_then_loc(%arg1 : i32 {foo.bar = 2 : i32} loc(unknown)) -> i32 {
      func.return %arg1 : i32
    }
``` 
xDSL raises parsing error because it doesn't expect location to be there
inside func.func block arguments.
```python
raise ParseError(at_position, msg)
xdsl.utils.exceptions.ParseError: parse_with_location.mlir:20:30
    func.func @f_attrs_then_loc(%arg1 : i32 {foo.bar = 2 : i32} loc(unknown)) -> i32 {
                             ^^^
                             ')' expected
``` 
while the same mlir code is parsed by mlir tools without any parsing
errors. MLIR also expects the location to be in a specific order like
`%arg: <type> {attr} loc(...)`
mlir supports this kind of location format for instance - 
```mlir
module {
  func.func @f(%arg0: i32 {foo.bar = 1 : i32} loc(unknown)) {
    func.return
  }
}
``` 
while if the order of location format is something like `%arg: <type>
loc(...) {attr}` , then it is not supported in MLIR -
```mlir
module {
  func.func @f(%arg0: i32 loc(unknown) {foo.bar = 1 : i32}) {
    func.return
  }
}
```

---------

Signed-off-by: Zahid Wakeel <zahid.wakeel@synthara.ai>