core: Move custom Operation verification 'verify_()' to end of verify function (#664)
At the moment the verification process for an Operation looks like this:

    def verify(self, verify_nested_ops: bool = True) -> None:
        for operand in self.operands:
            if isinstance(operand, ErasedSSAValue):
raise Exception("Erased SSA value is used by the operation")

        # Custom verifier
        self.verify_()

        # Verifier generated by irdl_op_def
        op_def = type(self).irdl_definition
        if op_def is not None:
            op_def.verify(self)

        if verify_nested_ops:
            for region in self.regions:
                region.verify()

    def verify_(self) -> None:
        pass
By doing the Custom Verifer before the irdl generated varifer when an
attribute is missed in the parsed input text (for example), it becomes
an ugly error when it is assumed to exist in the ``` verify_()->None ```
function:
```
... xdsl/xdsl/irdl.py", line 1179, in field_getter
    return self.attributes[attribute_name]
KeyError: 'opAttr_var_name'
```
whereas if the irdl generated verifier went first we get the slightly
nicer error:
```
xdsl.utils.exceptions.VerifyException: attribute opAttr_var_name expected
```
And there would be room, I assume, to make this error prettier in the
future, without users needing to worry about performing the same
verification checks in their custom ```verify_()``` functions.

---------

Co-authored-by: Sasha Lopoukhine <superlopuh@gmail.com>